export const ADD_PRODUCT = 'ADD_PRODUCT'
export const SUCCESS_PRODUCT = 'SUCCESS_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SUCCESS_PRODUCTS = 'SUCCESS_PRODUCTS'
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const SUCCESS_DELETE = 'SUCCESS_DELETE'
export const ERROR_DELETE = 'ERROR_DELETE'

export const CURRENT_PRODUCT = 'CURRENT_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const SUCCESS_EDIT = 'SUCCESS_EDIT'
export const ERROR_EDIT = 'ERROR_EDIT'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
